spring:
  application:
    name: note-xml

  # 기본 값: false
  h2:
    console:
      enabled: true

# 기본 값: h2-console
      path: /console        
  
# 봄은 기본으로 임의 이름 사용함
  datasource:
    generate-unique-name: false
    
# 기본 값 : testdb
    name: store
    
# 기본 값 : sa
    username: park
    
# 기본 값 : (없음)    
    password: 1234 